-- 0004 · down
DROP TABLE IF EXISTS dashboard_versions CASCADE;
DROP TABLE IF EXISTS dashboards CASCADE;
DROP TABLE IF EXISTS metric_definitions CASCADE;
DROP TABLE IF EXISTS fact_payment CASCADE;
DROP TABLE IF EXISTS fact_invoice CASCADE;
DROP TABLE IF EXISTS fact_order_line CASCADE;
DROP TABLE IF EXISTS fact_order CASCADE;
DROP TABLE IF EXISTS fact_lead CASCADE;
DROP TABLE IF EXISTS dim_stage CASCADE;
DROP TABLE IF EXISTS dim_product CASCADE;
DROP TABLE IF EXISTS dim_partner CASCADE;
DROP TABLE IF EXISTS dim_team CASCADE;
DROP TABLE IF EXISTS dim_user CASCADE;
DROP TABLE IF EXISTS dim_currency CASCADE;
DROP TABLE IF EXISTS dim_company CASCADE;
