/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as MappingRouteImport } from './routes/mapping'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiV1DataHealthRouteImport } from './routes/api/v1/data-health'
import { Route as ApiV1DiscoveryRouteImport } from './routes/api/v1/discovery'
import { Route as ApiV1SchemaSnapshotsRouteImport } from './routes/api/v1/schema-snapshots'
import { Route as ApiV1SessionRouteImport } from './routes/api/v1/session'
import { Route as ApiV1WorkspacesRouteImport } from './routes/api/v1/workspaces'
import { Route as ApiV1ConnectionsOdooRouteImport } from './routes/api/v1/connections.odoo'
import { Route as ApiV1ConnectionsOdooTestConnectionRouteImport } from './routes/api/v1/connections.odoo.test-connection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingRoute = MappingRouteImport.update({
  id: '/mapping',
  path: '/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DataHealthRoute = ApiV1DataHealthRouteImport.update({
  id: '/api/v1/data-health',
  path: '/api/v1/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DiscoveryRoute = ApiV1DiscoveryRouteImport.update({
  id: '/api/v1/discovery',
  path: '/api/v1/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SchemaSnapshotsRoute = ApiV1SchemaSnapshotsRouteImport.update({
  id: '/api/v1/schema-snapshots',
  path: '/api/v1/schema-snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SessionRoute = ApiV1SessionRouteImport.update({
  id: '/api/v1/session',
  path: '/api/v1/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WorkspacesRoute = ApiV1WorkspacesRouteImport.update({
  id: '/api/v1/workspaces',
  path: '/api/v1/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConnectionsOdooRoute = ApiV1ConnectionsOdooRouteImport.update({
  id: '/api/v1/connections/odoo',
  path: '/api/v1/connections/odoo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConnectionsOdooTestConnectionRoute =
  ApiV1ConnectionsOdooTestConnectionRouteImport.update({
    id: '/test-connection',
    path: '/test-connection',
    getParentRoute: () => ApiV1ConnectionsOdooRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/data-health': typeof DataHealthRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/data-health': typeof ApiV1DataHealthRoute
  '/api/v1/discovery': typeof ApiV1DiscoveryRoute
  '/api/v1/schema-snapshots': typeof ApiV1SchemaSnapshotsRoute
  '/api/v1/session': typeof ApiV1SessionRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRoute
  '/api/v1/connections/odoo': typeof ApiV1ConnectionsOdooRouteWithChildren
  '/api/v1/connections/odoo/test-connection': typeof ApiV1ConnectionsOdooTestConnectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/data-health': typeof DataHealthRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/data-health': typeof ApiV1DataHealthRoute
  '/api/v1/discovery': typeof ApiV1DiscoveryRoute
  '/api/v1/schema-snapshots': typeof ApiV1SchemaSnapshotsRoute
  '/api/v1/session': typeof ApiV1SessionRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRoute
  '/api/v1/connections/odoo': typeof ApiV1ConnectionsOdooRouteWithChildren
  '/api/v1/connections/odoo/test-connection': typeof ApiV1ConnectionsOdooTestConnectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRoute
  '/data-health': typeof DataHealthRoute
  '/mapping': typeof MappingRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/data-health': typeof ApiV1DataHealthRoute
  '/api/v1/discovery': typeof ApiV1DiscoveryRoute
  '/api/v1/schema-snapshots': typeof ApiV1SchemaSnapshotsRoute
  '/api/v1/session': typeof ApiV1SessionRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRoute
  '/api/v1/connections/odoo': typeof ApiV1ConnectionsOdooRouteWithChildren
  '/api/v1/connections/odoo/test-connection': typeof ApiV1ConnectionsOdooTestConnectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards'
    | '/data-health'
    | '/mapping'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/workspaces/new'
    | '/api/auth/$'
    | '/api/v1/data-health'
    | '/api/v1/discovery'
    | '/api/v1/schema-snapshots'
    | '/api/v1/session'
    | '/api/v1/workspaces'
    | '/api/v1/connections/odoo'
    | '/api/v1/connections/odoo/test-connection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboards'
    | '/data-health'
    | '/mapping'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/workspaces/new'
    | '/api/auth/$'
    | '/api/v1/data-health'
    | '/api/v1/discovery'
    | '/api/v1/schema-snapshots'
    | '/api/v1/session'
    | '/api/v1/workspaces'
    | '/api/v1/connections/odoo'
    | '/api/v1/connections/odoo/test-connection'
  id:
    | '__root__'
    | '/'
    | '/dashboards'
    | '/data-health'
    | '/mapping'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/api/health'
    | '/workspaces/new'
    | '/api/auth/$'
    | '/api/v1/data-health'
    | '/api/v1/discovery'
    | '/api/v1/schema-snapshots'
    | '/api/v1/session'
    | '/api/v1/workspaces'
    | '/api/v1/connections/odoo'
    | '/api/v1/connections/odoo/test-connection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardsRoute: typeof DashboardsRoute
  DataHealthRoute: typeof DataHealthRoute
  MappingRoute: typeof MappingRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiHealthRoute: typeof ApiHealthRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1DataHealthRoute: typeof ApiV1DataHealthRoute
  ApiV1DiscoveryRoute: typeof ApiV1DiscoveryRoute
  ApiV1SchemaSnapshotsRoute: typeof ApiV1SchemaSnapshotsRoute
  ApiV1SessionRoute: typeof ApiV1SessionRoute
  ApiV1WorkspacesRoute: typeof ApiV1WorkspacesRoute
  ApiV1ConnectionsOdooRoute: typeof ApiV1ConnectionsOdooRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping': {
      id: '/mapping'
      path: '/mapping'
      fullPath: '/mapping'
      preLoaderRoute: typeof MappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/data-health': {
      id: '/api/v1/data-health'
      path: '/api/v1/data-health'
      fullPath: '/api/v1/data-health'
      preLoaderRoute: typeof ApiV1DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/discovery': {
      id: '/api/v1/discovery'
      path: '/api/v1/discovery'
      fullPath: '/api/v1/discovery'
      preLoaderRoute: typeof ApiV1DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/schema-snapshots': {
      id: '/api/v1/schema-snapshots'
      path: '/api/v1/schema-snapshots'
      fullPath: '/api/v1/schema-snapshots'
      preLoaderRoute: typeof ApiV1SchemaSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/session': {
      id: '/api/v1/session'
      path: '/api/v1/session'
      fullPath: '/api/v1/session'
      preLoaderRoute: typeof ApiV1SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces': {
      id: '/api/v1/workspaces'
      path: '/api/v1/workspaces'
      fullPath: '/api/v1/workspaces'
      preLoaderRoute: typeof ApiV1WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/connections/odoo': {
      id: '/api/v1/connections/odoo'
      path: '/api/v1/connections/odoo'
      fullPath: '/api/v1/connections/odoo'
      preLoaderRoute: typeof ApiV1ConnectionsOdooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/connections/odoo/test-connection': {
      id: '/api/v1/connections/odoo/test-connection'
      path: '/test-connection'
      fullPath: '/api/v1/connections/odoo/test-connection'
      preLoaderRoute: typeof ApiV1ConnectionsOdooTestConnectionRouteImport
      parentRoute: typeof ApiV1ConnectionsOdooRoute
    }
  }
}

interface ApiV1ConnectionsOdooRouteChildren {
  ApiV1ConnectionsOdooTestConnectionRoute: typeof ApiV1ConnectionsOdooTestConnectionRoute
}

const ApiV1ConnectionsOdooRouteChildren: ApiV1ConnectionsOdooRouteChildren = {
  ApiV1ConnectionsOdooTestConnectionRoute:
    ApiV1ConnectionsOdooTestConnectionRoute,
}

const ApiV1ConnectionsOdooRouteWithChildren =
  ApiV1ConnectionsOdooRoute._addFileChildren(ApiV1ConnectionsOdooRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardsRoute: DashboardsRoute,
  DataHealthRoute: DataHealthRoute,
  MappingRoute: MappingRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiHealthRoute: ApiHealthRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1DataHealthRoute: ApiV1DataHealthRoute,
  ApiV1DiscoveryRoute: ApiV1DiscoveryRoute,
  ApiV1SchemaSnapshotsRoute: ApiV1SchemaSnapshotsRoute,
  ApiV1SessionRoute: ApiV1SessionRoute,
  ApiV1WorkspacesRoute: ApiV1WorkspacesRoute,
  ApiV1ConnectionsOdooRoute: ApiV1ConnectionsOdooRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
